import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
async function login(page:Page){const accounts=JSON.parse(readFileSync('.runtime/qa-account.json','utf8')) as {cookies:Parameters<BrowserContext['addCookies']>[0]}[];await page.context().addCookies(accounts[0]!.cookies);await page.goto('/resumen');}
async function pick(page:Page,label:string,text:string){const input=page.getByRole('combobox',{name:label,exact:true});await input.fill(text);await expect(page.getByRole('option').filter({hasText:text})).toBeVisible();await input.press('ArrowDown');await input.press('Enter');await expect(input).toHaveValue(text);}
test('catalogue fills editable order snapshots and archival preserves history',async({page})=>{
 await login(page);const stamp=Date.now();const product=`Producto QA ${stamp}`;const customer=`Cliente catálogo QA ${stamp}`;
 await page.goto('/productos/nuevo');await page.getByLabel('Nombre',{exact:false}).fill(product);await page.getByLabel('Precio (COP)',{exact:false}).fill('25000,50');await page.getByRole('button',{name:'Guardar producto',exact:true}).click();await expect(page.locator('h1')).toHaveText(product);const productUrl=page.url().split('?')[0]!;
 await page.goto('/pedidos/nuevo');await page.getByRole('button',{name:'+ Crear cliente',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Nombre (obligatorio)',{exact:true}).fill(customer);await dialog.getByRole('button',{name:'Guardar cliente',exact:true}).click();await expect(page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true})).toHaveValue(customer);
 await pick(page,'Producto · vela 1',product);await expect(page.getByLabel('Descripción de la vela')).toHaveValue(product);await expect(page.getByLabel('Precio unitario (COP)',{exact:true})).toHaveValue('25000,50');await page.getByLabel('Descripción de la vela').fill(product+' personalizado');await page.getByLabel('Precio unitario (COP)',{exact:true}).fill('24000');await page.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(page.locator('.order-total')).toContainText('24.000');const orderUrl=page.url();
 await page.goto(productUrl+'/editar');await page.getByLabel('Nombre',{exact:false}).fill(product+' nuevo');await page.getByLabel('Precio (COP)',{exact:false}).fill('30000');await page.getByRole('button',{name:'Guardar producto',exact:true}).click();await expect(page.locator('h1')).toHaveText(product+' nuevo');await page.getByRole('button',{name:'Archivar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Archivar',exact:true}).click();await expect(page.getByText('REGISTRO ARCHIVADO',{exact:true})).toBeVisible();
 await page.goto(orderUrl);await expect(page.locator('.detail-lines')).toContainText(product+' personalizado');await expect(page.locator('.order-total')).toContainText('24.000');await page.getByRole('link',{name:'Editar',exact:true}).click();await expect(page.getByLabel('Descripción de la vela')).toHaveValue(product+' personalizado');await page.getByRole('button',{name:'Usar línea personalizada',exact:true}).click();await expect(page.getByRole('combobox',{name:'Producto · vela 1',exact:true})).toHaveValue('');await expect(page.getByLabel('Descripción de la vela')).toHaveValue(product+' personalizado');await page.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(page.locator('.order-total')).toContainText('24.000');
 await page.goto('/pedidos/nuevo');await page.getByRole('combobox',{name:'Producto · vela 1',exact:true}).fill(product);await expect(page.getByText('Sin coincidencias',{exact:true})).toBeVisible();
 await page.goto(productUrl);await page.getByRole('button',{name:'Restaurar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Restaurar',exact:true}).click();await expect(page.getByText('Registro restaurado',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Consultar historial',exact:true}).click();await expect(page.locator('.history-list')).toContainText('Restaurado');
});
test('search rejects stale options and unmatched customer text',async({page})=>{
 await login(page);const customer=`Busqueda QA ${Date.now()}`;await page.goto('/clientes/nuevo');await page.getByLabel('Nombre',{exact:false}).fill(customer);await page.getByRole('button',{name:'Guardar cliente',exact:true}).click();await expect(page.locator('h1')).toHaveText(customer);
 await page.goto('/pedidos/nuevo');const input=page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true});await input.fill(customer);await expect(page.getByRole('option',{name:customer,exact:true})).toBeVisible();await input.fill('Sin coincidencia XYZ');await input.press('ArrowDown');await input.press('Enter');await page.getByLabel('Descripción de la vela').fill('Vela personalizada');await page.getByLabel('Precio unitario (COP)',{exact:true}).fill('100');await page.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(page.locator('#field-customerId-error')).toContainText('Selecciona un cliente');await pick(page,'Cliente (obligatorio)',customer);
});
test('daily and monthly analytics have exact accessible values and zero periods',async({page})=>{
 await login(page);await page.getByLabel('Desde',{exact:true}).fill('2090-01-01');await page.getByLabel('Hasta',{exact:true}).fill('2090-01-03');await page.getByRole('button',{name:'Consultar',exact:true}).click();await expect(page.getByText('Por día · COP',{exact:true})).toBeVisible();await page.getByText('Ver valores exactos',{exact:true}).click();await expect(page.locator('.chart-table tbody tr')).toHaveCount(3);await expect(page.locator('.chart-table tbody')).toContainText('COP 0');await expect(page.locator('.evolution-chart')).toBeVisible();await page.getByLabel('Hasta',{exact:true}).fill('2090-03-02');await page.getByRole('button',{name:'Consultar',exact:true}).click();await expect(page.getByText('Por mes · COP',{exact:true})).toBeVisible();await expect(page.locator('.chart-table tbody tr')).toHaveCount(3);await expect(page.getByText('No representa utilidad contable ni saldo de caja.',{exact:true})).toBeVisible();
});
for(const width of [360,768,1440])test(`compact order and products fit ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await login(page);await page.goto('/pedidos/nuevo');await page.getByRole('button',{name:'+ Añadir vela',exact:true}).click();await page.getByRole('button',{name:'+ Añadir vela',exact:true}).click();await expect(page.locator('.compact-line')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===1440){for(const selector of ['#field-customerId','#field-orderDate','.savebar-total','button[type="submit"]']){const rect=await page.locator(selector).boundingBox();expect(rect).not.toBeNull();expect(rect!.y).toBeGreaterThanOrEqual(0);expect(rect!.y+rect!.height).toBeLessThanOrEqual(900);}}
 await page.goto('/productos');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width===360){await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('dialog').getByRole('link',{name:'Productos',exact:true}).click();await expect(page).toHaveURL(/productos/);}
});
