import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {parse} from 'dotenv';
import pg from 'pg';
async function login(page:Page){const accounts=JSON.parse(readFileSync('.runtime/qa-account.json','utf8')) as {cookies:Parameters<BrowserContext['addCookies']>[0]}[];await page.context().addCookies(accounts[0]!.cookies);await page.goto('/resumen');}
async function fixtures(){const url=new URL(parse(readFileSync('.runtime/test-migrator.env'))['DATABASE_URL']??'');if(url.pathname!=='/lumina_test'||url.hostname!=='127.0.0.1')throw new Error('Isolated QA DB required');const db=new pg.Client({connectionString:url.href});await db.connect();const token=randomUUID().slice(0,8);const names=[`Cliente QA antiguo ${token}`,`Cliente QA nuevo ${token}`];const product=`Vela QA precio ${token}`;const productId=randomUUID();for(const name of names)await db.query('INSERT INTO customers(id,name,"updatedAt") VALUES($1,$2,now())',[randomUUID(),name]);await db.query('INSERT INTO products(id,name,price,"updatedAt") VALUES($1,$2,$3,now())',[productId,product,'500.50']);return {db,names,product,productId,token};}
test('independent QA: old options vanish immediately and late search responses cannot replace new selection',async({page})=>{
 const {db,names}=await fixtures();try{
  await login(page);await page.goto('/pedidos/nuevo');const input=page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true});
  await input.fill(names[0]!);await expect(page.getByRole('option',{name:names[0],exact:true})).toBeVisible();await input.fill('QA sin coincidencia '+randomUUID());await expect(page.getByRole('option')).toHaveCount(0);await input.press('ArrowDown');await input.press('Enter');await input.press('Tab');await expect(input).toHaveValue('');
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});let arrived!:()=>void;const captured=new Promise<void>(resolve=>{arrived=resolve;});let delivered!:()=>void;const complete=new Promise<void>(resolve=>{delivered=resolve;});
  await page.route('**/pedidos/nuevo',async route=>{const request=route.request();if(request.method()==='POST'&&request.postData()?.includes('clients.list')&&request.postData()?.includes(names[0]!)){const response=await route.fetch();arrived();await gate;await route.fulfill({response});delivered();}else await route.continue();});
  await input.fill(names[0]!);await captured;await input.fill(names[1]!);await expect(page.getByRole('option')).toHaveCount(0);release();await complete;await expect(page.getByRole('option',{name:names[1],exact:true})).toBeVisible();await input.press('ArrowDown');await input.press('Enter');await expect(input).toHaveValue(names[1]!);await expect(page.getByRole('option',{name:names[0],exact:true})).toHaveCount(0);
 }finally{await db.end();}
});
test('independent QA: selected price comes from visible fresh option, cross-line searches preserve it and save disables comboboxes',async({page})=>{
 const {db,names,product,productId,token}=await fixtures();try{
  await login(page);await page.goto('/pedidos/nuevo');const customer=page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true});await customer.fill(names[1]!);await page.getByRole('option',{name:names[1],exact:true}).click();
  const input=page.getByRole('combobox',{name:'Producto · vela 1',exact:true});let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});let arrived!:()=>void;const captured=new Promise<void>(resolve=>{arrived=resolve;});let delivered!:()=>void;const complete=new Promise<void>(resolve=>{delivered=resolve;});
  await page.route('**/pedidos/nuevo',async route=>{const request=route.request();if(request.method()==='POST'&&request.postData()?.includes('products.list')&&request.postData()?.includes(product)){const response=await route.fetch();arrived();await gate;await route.fulfill({response});delivered();}else await route.continue();});
  await input.fill(product);await captured;await db.query('UPDATE products SET price=$1 WHERE id=$2',['999.90',productId]);await input.fill(token);await expect(page.getByRole('option')).toHaveCount(0);release();await complete;await expect(page.getByRole('option').filter({hasText:product})).toContainText('999,90');await page.getByRole('option').filter({hasText:product}).click();await expect(page.getByLabel('Precio unitario (COP)',{exact:true})).toHaveValue('999,90');
  await page.getByLabel('Cantidad',{exact:true}).fill('3');await page.getByRole('button',{name:'+ Añadir vela',exact:true}).click();await page.getByRole('combobox',{name:'Producto · vela 2',exact:true}).fill('Sin producto '+randomUUID());await expect(page.getByText('Sin coincidencias',{exact:true})).toBeVisible();await page.getByLabel('Descripción de la vela').nth(1).fill('Vela libre QA');await page.getByLabel('Precio unitario (COP)',{exact:true}).nth(1).fill('100');await expect(page.getByLabel('Precio unitario (COP)',{exact:true}).first()).toHaveValue('999,90');await expect(page.getByLabel('Cantidad',{exact:true}).first()).toHaveValue('3');
  await page.getByRole('button',{name:'+ Añadir vela',exact:true}).click();await page.getByLabel('Descripción de la vela').nth(2).fill('Tercera vela libre QA');await page.getByLabel('Precio unitario (COP)',{exact:true}).nth(2).fill('200');
  for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/qa-visual/improvements-order-${width}.png`,fullPage:true});await page.screenshot({path:`docs/qa-visual/improvements-order-viewport-${width}.png`,fullPage:false});if(width===1440){for(const selector of ['#field-customerId','#field-orderDate','.savebar-total','button[type="submit"]']){const rect=await page.locator(selector).boundingBox();expect(rect!.y).toBeGreaterThanOrEqual(0);expect(rect!.y+rect!.height).toBeLessThanOrEqual(900);}}}
  let releaseSave!:()=>void;const saveGate=new Promise<void>(resolve=>{releaseSave=resolve;});await page.route('**/pedidos/nuevo',async route=>{if(route.request().method()==='POST'&&route.request().postData()?.includes('orders.create')){await saveGate;await route.continue();}else await route.fallback();});
  await page.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(page.getByRole('button',{name:'Guardando…',exact:true})).toBeDisabled();for(const combobox of await page.getByRole('combobox').all())await expect(combobox).toBeDisabled();await expect(page.getByRole('listbox')).toHaveCount(0);releaseSave();await expect(page.locator('.order-total')).toContainText('3.299,70');
 }finally{await db.end();}
});
test('independent QA: late failed search does not replace newer successful options',async({page})=>{
 const {db,names}=await fixtures();try{
  await login(page);await page.goto('/pedidos/nuevo');const input=page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true});let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});let arrived!:()=>void;const captured=new Promise<void>(resolve=>{arrived=resolve;});let delivered!:()=>void;const complete=new Promise<void>(resolve=>{delivered=resolve;});
  await page.route('**/pedidos/nuevo',async route=>{if(route.request().method()==='POST'&&route.request().postData()?.includes('clients.list')&&route.request().postData()?.includes(names[0]!)){arrived();await gate;await route.abort('failed');delivered();}else await route.continue();});
  await input.fill(names[0]!);await captured;await input.fill(names[1]!);await expect(page.getByRole('option')).toHaveCount(0);release();await complete;await expect(page.getByRole('option',{name:names[1],exact:true})).toBeVisible();await input.press('ArrowDown');await input.press('Enter');await expect(input).toHaveValue(names[1]!);await expect(page.getByText('No pudimos buscar. Vuelve a intentarlo.',{exact:true})).toHaveCount(0);
 }finally{await db.end();}
});
test('independent QA: real touch contexts select client and product with accessible 44px actions',async({browser})=>{
 const {db,names,product}=await fixtures();try{
  for(const width of [360,768]){
   const context=await browser.newContext({hasTouch:true,viewport:{width,height:900}});try{
    const page=await context.newPage();await login(page);await page.goto('/pedidos/nuevo');await page.getByRole('button',{name:'Guardar pedido',exact:true}).tap();
    const customer=page.getByRole('combobox',{name:'Cliente (obligatorio)',exact:true});await expect(customer).toHaveAttribute('aria-invalid','true');const error=await customer.getAttribute('aria-describedby');await expect(page.locator(`[id="${error}"]`)).toContainText('Selecciona un cliente');await customer.tap();await customer.fill(names[1]!);await page.getByRole('option',{name:names[1],exact:true}).tap();await expect(customer).toHaveValue(names[1]!);
    const item=page.getByRole('combobox',{name:'Producto · vela 1',exact:true});await item.tap();await item.fill(product);await page.getByRole('option').filter({hasText:product}).tap();await expect(item).toHaveValue(product);await expect(page.locator('[id="field-lines.0.unitPrice"]')).toHaveValue('500,50');
    const custom=page.getByRole('button',{name:'Usar línea personalizada',exact:true});const rect=await custom.boundingBox();expect(rect!.height).toBeGreaterThanOrEqual(44);await custom.tap();await expect(item).toHaveValue('');await expect(page.locator('[id="field-lines.0.unitPrice"]')).toHaveValue('500,50');
    const save=await page.getByRole('button',{name:'Guardar pedido',exact:true}).boundingBox();expect(save!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
   }finally{await context.close();}
  }
 }finally{await db.end();}
});
test('independent QA: negative exact monthly table matches metrics and renders bounded signed chart',async({page})=>{
 const {db,names}=await fixtures();const orderId=randomUUID();const expenseId=randomUUID();try{
  const customer=await db.query('SELECT id FROM customers WHERE name=$1',[names[0]]);
  await db.query('INSERT INTO sales_orders(id,"customerId","customerNameSnapshot","orderDate",total,"updatedAt") VALUES($1,$2,$3,$4,$5,now())',[orderId,customer.rows[0].id,names[0],'2077-01-15','0.20']);
  await db.query('INSERT INTO sales_order_lines(id,"orderId",position,description,quantity,"unitPrice") VALUES($1,$2,1,$3,2,$4)',[randomUUID(),orderId,'Dos velas sintéticas pequeñas','0.10']);
  await db.query('INSERT INTO expenses(id,"expenseDate",concept,amount,"updatedAt") VALUES($1,$2,$3,$4,now())',[expenseId,'2077-01-15','Gasto sintético negativo exacto','0.30']);
  await login(page);await page.getByLabel('Desde',{exact:true}).fill('2077-01-15');await page.getByLabel('Hasta',{exact:true}).fill('2077-03-15');await page.getByRole('button',{name:'Consultar',exact:true}).click();await expect(page.getByText('Por mes · COP',{exact:true})).toBeVisible();
  await expect(page.locator('.metric-orders')).toContainText('0,20');await expect(page.locator('.metric-expenses')).toContainText('0,30');await expect(page.locator('.metric-difference')).toContainText(/\u2212\s*(?:COP\s*)?0,10/);await page.getByText('Ver valores exactos',{exact:true}).click();await expect(page.locator('.chart-table tbody tr')).toHaveCount(3);
  const row=page.locator('.chart-table tbody tr').first();await expect(row.locator('td').nth(0)).toContainText('0,20');await expect(row.locator('td').nth(1)).toContainText('0,30');await expect(row.locator('td').nth(2)).toContainText(/\u2212\s*(?:COP\s*)?0,10/);await expect(page.locator('.chart-table tbody tr').nth(1)).toContainText('COP 0');await expect(page.locator('.evolution-chart')).toContainText(/\u2212\s*(?:COP\s*)?0,10/);
  for(const polyline of await page.locator('.evolution-chart polyline').all()){const points=await polyline.getAttribute('points');expect(points).not.toMatch(/NaN|Infinity/);expect(points!.split(' ')).toHaveLength(3);}
  for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});await page.locator('.evolution-section').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/qa-visual/improvements-chart-viewport-${width}.png`,fullPage:false});}
 }finally{await db.query('DELETE FROM sales_order_lines WHERE "orderId"=$1',[orderId]);await db.query('DELETE FROM sales_orders WHERE id=$1',[orderId]);await db.query('DELETE FROM expenses WHERE id=$1',[expenseId]);await db.end();}
});
