 'use client';
import { useEffect, useId, useRef, useState } from 'react';
export interface Choice {id:string;label:string;detail?:string;price?:string}
export function SearchCombobox({label,id,value,selected,onSelect,search,error,disabled=false,placeholder='Buscar…'}:{label:string;id:string;value:string;selected?:Choice;onSelect:(choice:Choice|null)=>void;search:(text:string)=>Promise<Choice[]>;error?:string;disabled?:boolean;placeholder?:string}) {
 const listId=useId();const [query,setQuery]=useState('');const [editing,setEditing]=useState(false);const [open,setOpen]=useState(false);const [items,setItems]=useState<Choice[]>([]);const [active,setActive]=useState(-1);const [loading,setLoading]=useState(false);const [failure,setFailure]=useState('');const sequence=useRef(0);const searchRef=useRef(search);
 useEffect(()=>{searchRef.current=search;},[search]);
 useEffect(()=>{if(!open||disabled)return;const current=++sequence.current;let cancelled=false;const timer=setTimeout(()=>{void searchRef.current(query).then(found=>{if(!cancelled&&current===sequence.current){setItems(found);setActive(-1);}}).catch(()=>{if(!cancelled&&current===sequence.current){setItems([]);setFailure('No pudimos buscar. Vuelve a intentarlo.');}}).finally(()=>{if(!cancelled&&current===sequence.current)setLoading(false);});},220);return()=>{clearTimeout(timer);cancelled=true;};},[query,open,disabled]);
 function resetSearch(){sequence.current++;setItems([]);setActive(-1);setLoading(true);setFailure('');}
 function reopen(){if(disabled)return;resetSearch();setQuery(editing?query:selected?.label??'');setOpen(true);}
 function choose(choice:Choice){if(disabled||loading||!items.some(item=>item.id===choice.id))return;onSelect(choice);setEditing(false);setOpen(false);sequence.current++;}
 const expanded=open&&!disabled;
 useEffect(()=>{if(expanded&&active>=0)document.getElementById(`${listId}-${active}`)?.scrollIntoView({block:'nearest'});},[expanded,active,listId]);
 return <div className="combobox"><label htmlFor={id}>{label}</label><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={expanded} aria-controls={listId} aria-activedescendant={expanded&&active>=0?`${listId}-${active}`:undefined} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} autoComplete="off" maxLength={120} disabled={disabled} value={editing?query:selected?.label??''} placeholder={placeholder} onFocus={()=>{if(!open)reopen();}} onBlur={()=>{setOpen(false);setEditing(false);sequence.current++;}} onChange={e=>{resetSearch();setQuery(e.target.value);setEditing(true);onSelect(null);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);sequence.current++;return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!open){reopen();return;}setActive(previous=>items.length?Math.max(0,Math.min(items.length-1,previous+(e.key==='ArrowDown'?1:-1))):-1);}if(e.key==='Enter'&&open){e.preventDefault();if(active>=0&&items[active])choose(items[active]);}}}/>{error&&<small className="field-error" id={`${id}-error`}>{error}</small>}{expanded&&<div className="combobox-popup"><ul role="listbox" id={listId} aria-label={label}>{items.map((choice,index)=><li id={`${listId}-${index}`} key={choice.id} role="option" aria-selected={choice.id===value} className={active===index?'active':''} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(choice)}><strong>{choice.label}</strong>{choice.detail&&<small>{choice.detail}</small>}</li>)}</ul><div className="combobox-status" role="status">{loading?'Buscando…':failure||(!items.length?'Sin coincidencias':'')}</div></div>}</div>;
}
